spring.config.import=optional:file:.env[.properties]

spring.application.name=AndefRacing-Backend

server.port=${PORT:8080}
server.address=0.0.0.0

# Multipart
upload.path=${UPLOAD_PATH:/uploads}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# PostgreSQL
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# JPA
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:validate}

# JWT
jwt.secret-key=${JWT_SECRET_KEY}
jwt.expiration-millis=${JWT_EXPIRATION_MILLIS}

# API versioning
spring.mvc.apiversion.default=1.0.0
spring.mvc.apiversion.use.header=X-Version

# Render Key Value / Redis
spring.data.redis.url=${REDIS_URL}
spring.data.redis.timeout=2000ms